# Generated by Django 2.2.4 on 2019-09-13 16:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=2000, null=True, verbose_name='comment')),
                ('project_owner', models.CharField(blank=True, max_length=50, null=True, verbose_name='project owner')),
                ('user_requirements', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='user requirements (%)')),
                ('user_comment', models.TextField(blank=True, max_length=3000, null=True, verbose_name='remarks')),
                ('development', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='development (%)')),
                ('dev_comment', models.TextField(blank=True, max_length=3000, null=True, verbose_name='remarks')),
                ('sit', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='SIT (%)')),
                ('sit_comment', models.TextField(blank=True, max_length=3000, null=True, verbose_name='remarks')),
                ('uat', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='UAT (%)')),
                ('uat_comment', models.TextField(blank=True, max_length=3000, null=True, verbose_name='remarks')),
                ('implementation', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Implementation (%)')),
                ('imp_comment', models.TextField(blank=True, max_length=3000, null=True, verbose_name='remarks')),
                ('is_done', models.BooleanField(default=False, verbose_name='done?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_status_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.Task')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL, verbose_name='PIC IT')),
            ],
            options={
                'verbose_name': 'Project Status',
                'verbose_name_plural': 'Projects Status',
                'ordering': ['task'],
            },
        ),
    ]
